(() => {
 const q=new URLSearchParams(location.search), es=q.get('pais')==='sv', beer=q.get('propuesta')==='beercave';
 const bar=document.createElement('nav');bar.id='country-nav';bar.setAttribute('aria-label','País y propuesta');
 bar.innerHTML='<label>País <select id="country-select" aria-label="País"><option value="rd">República Dominicana</option><option value="sv">El Salvador</option><option value="pa" disabled>Panamá · Próximamente</option></select></label><label id="proposal-label">Versión <select id="proposal-select" aria-label="Versión de El Salvador"><option value="original">Original</option><option value="beercave">Propuesta con Beer Cave</option></select></label><span>Carga únicamente el modelo seleccionado</span>';
 document.querySelector('header').after(bar);document.querySelector('#country-select').value=es?'sv':'rd';document.querySelector('#proposal-select').value=beer?'beercave':'original';document.querySelector('#proposal-label').hidden=!es;
 const style=document.createElement('style');style.textContent='#country-nav{display:flex;align-items:center;gap:18px;padding:8px 20px;background:#fff;border-bottom:1px solid #ddd;flex:none}#country-nav label{display:flex;align-items:center;gap:10px;margin:0;font-size:12px;font-weight:600}#country-nav select{width:auto;max-width:270px;padding:8px}#country-nav span{font-size:11px;color:#68717b}#country-nav [hidden]{display:none!important}body{height:100dvh;display:flex;flex-direction:column;overflow:hidden}body>header{flex:none}body>main{flex:1;min-height:0;height:auto}@media(max-width:700px){#country-nav{flex-wrap:wrap;gap:8px;padding:7px}#country-nav span{display:none}#country-nav select{max-width:200px}}';document.head.append(style);
 function go(country,proposal){const u=new URL('./',location.href);u.searchParams.set('pais',country);if(country==='sv')u.searchParams.set('propuesta',proposal);window.top.location.href=u.href;}
 document.querySelector('#country-select').onchange=e=>go(e.target.value,'original');document.querySelector('#proposal-select').onchange=e=>go('sv',e.target.value);
})();
